version: '3'

services:
  
  nginx:
    image: nginx
    container_name: esg-frontend-nginx
    ports:
      - 80:80
    links:
      - nextjs
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  nextjs:
    image: esg-frontend
    container_name: esg-frontend-nextjs
    expose:
      - 3000
